// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adj_Real
SEXP adj_Real(double v);
RcppExport SEXP _xadr_adj_Real(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_Real(v));
    return rcpp_result_gen;
END_RCPP
}
// adj_getValue
double adj_getValue(SEXP xptr);
RcppExport SEXP _xadr_adj_getValue(SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_getValue(xptr));
    return rcpp_result_gen;
END_RCPP
}
// adj_getDerivative
double adj_getDerivative(SEXP xptr);
RcppExport SEXP _xadr_adj_getDerivative(SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_getDerivative(xptr));
    return rcpp_result_gen;
END_RCPP
}
// adj_setDerivative
void adj_setDerivative(SEXP xptr, double d);
RcppExport SEXP _xadr_adj_setDerivative(SEXP xptrSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    adj_setDerivative(xptr, d);
    return R_NilValue;
END_RCPP
}
// adj_createTape
SEXP adj_createTape();
RcppExport SEXP _xadr_adj_createTape() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(adj_createTape());
    return rcpp_result_gen;
END_RCPP
}
// adj_deactivateTape
void adj_deactivateTape(SEXP tape_ptr);
RcppExport SEXP _xadr_adj_deactivateTape(SEXP tape_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    adj_deactivateTape(tape_ptr);
    return R_NilValue;
END_RCPP
}
// adj_deactivateAll
void adj_deactivateAll();
RcppExport SEXP _xadr_adj_deactivateAll() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    adj_deactivateAll();
    return R_NilValue;
END_RCPP
}
// adj_registerInput
void adj_registerInput(SEXP tape_ptr, SEXP xptr);
RcppExport SEXP _xadr_adj_registerInput(SEXP tape_ptrSEXP, SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    adj_registerInput(tape_ptr, xptr);
    return R_NilValue;
END_RCPP
}
// adj_registerOutput
void adj_registerOutput(SEXP tape_ptr, SEXP xptr);
RcppExport SEXP _xadr_adj_registerOutput(SEXP tape_ptrSEXP, SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    adj_registerOutput(tape_ptr, xptr);
    return R_NilValue;
END_RCPP
}
// adj_newRecording
void adj_newRecording(SEXP tape_ptr);
RcppExport SEXP _xadr_adj_newRecording(SEXP tape_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    adj_newRecording(tape_ptr);
    return R_NilValue;
END_RCPP
}
// adj_computeAdjoints
void adj_computeAdjoints(SEXP tape_ptr);
RcppExport SEXP _xadr_adj_computeAdjoints(SEXP tape_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    adj_computeAdjoints(tape_ptr);
    return R_NilValue;
END_RCPP
}
// adj_clearDerivatives
void adj_clearDerivatives(SEXP tape_ptr);
RcppExport SEXP _xadr_adj_clearDerivatives(SEXP tape_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_ptr(tape_ptrSEXP);
    adj_clearDerivatives(tape_ptr);
    return R_NilValue;
END_RCPP
}
// adj_add
SEXP adj_add(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_add(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_add(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_add_scalar
SEXP adj_add_scalar(SEXP a, double b);
RcppExport SEXP _xadr_adj_add_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_add_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_sub
SEXP adj_sub(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_sub(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_sub(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_sub_scalar
SEXP adj_sub_scalar(SEXP a, double b);
RcppExport SEXP _xadr_adj_sub_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_sub_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_mul
SEXP adj_mul(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_mul(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_mul(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_mul_scalar
SEXP adj_mul_scalar(SEXP a, double b);
RcppExport SEXP _xadr_adj_mul_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_mul_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_div
SEXP adj_div(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_div(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_div(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_div_scalar
SEXP adj_div_scalar(SEXP a, double b);
RcppExport SEXP _xadr_adj_div_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_div_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_neg
SEXP adj_neg(SEXP a);
RcppExport SEXP _xadr_adj_neg(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_neg(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_sin
SEXP adj_sin(SEXP a);
RcppExport SEXP _xadr_adj_sin(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_sin(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_cos
SEXP adj_cos(SEXP a);
RcppExport SEXP _xadr_adj_cos(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_cos(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_tan
SEXP adj_tan(SEXP a);
RcppExport SEXP _xadr_adj_tan(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_tan(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_asin
SEXP adj_asin(SEXP a);
RcppExport SEXP _xadr_adj_asin(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_asin(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_acos
SEXP adj_acos(SEXP a);
RcppExport SEXP _xadr_adj_acos(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_acos(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_atan
SEXP adj_atan(SEXP a);
RcppExport SEXP _xadr_adj_atan(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_atan(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_atan2
SEXP adj_atan2(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_atan2(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_atan2(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_exp
SEXP adj_exp(SEXP a);
RcppExport SEXP _xadr_adj_exp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_exp(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_exp2
SEXP adj_exp2(SEXP a);
RcppExport SEXP _xadr_adj_exp2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_exp2(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_expm1
SEXP adj_expm1(SEXP a);
RcppExport SEXP _xadr_adj_expm1(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_expm1(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_log
SEXP adj_log(SEXP a);
RcppExport SEXP _xadr_adj_log(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_log(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_log2
SEXP adj_log2(SEXP a);
RcppExport SEXP _xadr_adj_log2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_log2(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_log10
SEXP adj_log10(SEXP a);
RcppExport SEXP _xadr_adj_log10(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_log10(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_log1p
SEXP adj_log1p(SEXP a);
RcppExport SEXP _xadr_adj_log1p(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_log1p(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_sqrt
SEXP adj_sqrt(SEXP a);
RcppExport SEXP _xadr_adj_sqrt(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_sqrt(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_cbrt
SEXP adj_cbrt(SEXP a);
RcppExport SEXP _xadr_adj_cbrt(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_cbrt(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_pow
SEXP adj_pow(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_pow(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_pow(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_pow_scalar
SEXP adj_pow_scalar(SEXP a, double b);
RcppExport SEXP _xadr_adj_pow_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_pow_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_abs
SEXP adj_abs(SEXP a);
RcppExport SEXP _xadr_adj_abs(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_abs(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_fabs
SEXP adj_fabs(SEXP a);
RcppExport SEXP _xadr_adj_fabs(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_fabs(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_sinh
SEXP adj_sinh(SEXP a);
RcppExport SEXP _xadr_adj_sinh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_sinh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_cosh
SEXP adj_cosh(SEXP a);
RcppExport SEXP _xadr_adj_cosh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_cosh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_tanh
SEXP adj_tanh(SEXP a);
RcppExport SEXP _xadr_adj_tanh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_tanh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_asinh
SEXP adj_asinh(SEXP a);
RcppExport SEXP _xadr_adj_asinh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_asinh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_acosh
SEXP adj_acosh(SEXP a);
RcppExport SEXP _xadr_adj_acosh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_acosh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_atanh
SEXP adj_atanh(SEXP a);
RcppExport SEXP _xadr_adj_atanh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_atanh(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_erf
SEXP adj_erf(SEXP a);
RcppExport SEXP _xadr_adj_erf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_erf(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_erfc
SEXP adj_erfc(SEXP a);
RcppExport SEXP _xadr_adj_erfc(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_erfc(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_floor
SEXP adj_floor(SEXP a);
RcppExport SEXP _xadr_adj_floor(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_floor(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_ceil
SEXP adj_ceil(SEXP a);
RcppExport SEXP _xadr_adj_ceil(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_ceil(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_round
SEXP adj_round(SEXP a);
RcppExport SEXP _xadr_adj_round(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_round(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_trunc
SEXP adj_trunc(SEXP a);
RcppExport SEXP _xadr_adj_trunc(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_trunc(a));
    return rcpp_result_gen;
END_RCPP
}
// adj_min
SEXP adj_min(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_min(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_min(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_max
SEXP adj_max(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_max(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_max(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_fmax
SEXP adj_fmax(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_fmax(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_fmax(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_fmin
SEXP adj_fmin(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_fmin(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_fmin(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_hypot
SEXP adj_hypot(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_hypot(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_hypot(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_ldexp
SEXP adj_ldexp(SEXP a, int exp);
RcppExport SEXP _xadr_adj_ldexp(SEXP aSEXP, SEXP expSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type exp(expSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_ldexp(a, exp));
    return rcpp_result_gen;
END_RCPP
}
// adj_fmod
SEXP adj_fmod(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_fmod(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_fmod(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_remainder
SEXP adj_remainder(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_remainder(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_remainder(a, b));
    return rcpp_result_gen;
END_RCPP
}
// adj_copysign
SEXP adj_copysign(SEXP a, SEXP b);
RcppExport SEXP _xadr_adj_copysign(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(adj_copysign(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_Real
SEXP fwd_Real(double v);
RcppExport SEXP _xadr_fwd_Real(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_Real(v));
    return rcpp_result_gen;
END_RCPP
}
// fwd_getValue
double fwd_getValue(SEXP xptr);
RcppExport SEXP _xadr_fwd_getValue(SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_getValue(xptr));
    return rcpp_result_gen;
END_RCPP
}
// fwd_getDerivative
double fwd_getDerivative(SEXP xptr);
RcppExport SEXP _xadr_fwd_getDerivative(SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_getDerivative(xptr));
    return rcpp_result_gen;
END_RCPP
}
// fwd_setDerivative
void fwd_setDerivative(SEXP xptr, double d);
RcppExport SEXP _xadr_fwd_setDerivative(SEXP xptrSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    fwd_setDerivative(xptr, d);
    return R_NilValue;
END_RCPP
}
// fwd_add
SEXP fwd_add(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_add(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_add(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_add_scalar
SEXP fwd_add_scalar(SEXP a, double b);
RcppExport SEXP _xadr_fwd_add_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_add_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_sub
SEXP fwd_sub(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_sub(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_sub(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_sub_scalar
SEXP fwd_sub_scalar(SEXP a, double b);
RcppExport SEXP _xadr_fwd_sub_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_sub_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_mul
SEXP fwd_mul(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_mul(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_mul(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_mul_scalar
SEXP fwd_mul_scalar(SEXP a, double b);
RcppExport SEXP _xadr_fwd_mul_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_mul_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_div
SEXP fwd_div(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_div(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_div(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_div_scalar
SEXP fwd_div_scalar(SEXP a, double b);
RcppExport SEXP _xadr_fwd_div_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_div_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_neg
SEXP fwd_neg(SEXP a);
RcppExport SEXP _xadr_fwd_neg(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_neg(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_pow
SEXP fwd_pow(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_pow(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_pow(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_pow_scalar
SEXP fwd_pow_scalar(SEXP a, double b);
RcppExport SEXP _xadr_fwd_pow_scalar(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_pow_scalar(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_sin
SEXP fwd_sin(SEXP a);
RcppExport SEXP _xadr_fwd_sin(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_sin(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_cos
SEXP fwd_cos(SEXP a);
RcppExport SEXP _xadr_fwd_cos(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_cos(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_tan
SEXP fwd_tan(SEXP a);
RcppExport SEXP _xadr_fwd_tan(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_tan(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_asin
SEXP fwd_asin(SEXP a);
RcppExport SEXP _xadr_fwd_asin(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_asin(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_acos
SEXP fwd_acos(SEXP a);
RcppExport SEXP _xadr_fwd_acos(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_acos(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_atan
SEXP fwd_atan(SEXP a);
RcppExport SEXP _xadr_fwd_atan(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_atan(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_atan2
SEXP fwd_atan2(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_atan2(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_atan2(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_exp
SEXP fwd_exp(SEXP a);
RcppExport SEXP _xadr_fwd_exp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_exp(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_exp2
SEXP fwd_exp2(SEXP a);
RcppExport SEXP _xadr_fwd_exp2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_exp2(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_expm1
SEXP fwd_expm1(SEXP a);
RcppExport SEXP _xadr_fwd_expm1(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_expm1(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_log
SEXP fwd_log(SEXP a);
RcppExport SEXP _xadr_fwd_log(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_log(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_log2
SEXP fwd_log2(SEXP a);
RcppExport SEXP _xadr_fwd_log2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_log2(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_log10
SEXP fwd_log10(SEXP a);
RcppExport SEXP _xadr_fwd_log10(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_log10(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_log1p
SEXP fwd_log1p(SEXP a);
RcppExport SEXP _xadr_fwd_log1p(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_log1p(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_sqrt
SEXP fwd_sqrt(SEXP a);
RcppExport SEXP _xadr_fwd_sqrt(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_sqrt(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_cbrt
SEXP fwd_cbrt(SEXP a);
RcppExport SEXP _xadr_fwd_cbrt(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_cbrt(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_abs
SEXP fwd_abs(SEXP a);
RcppExport SEXP _xadr_fwd_abs(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_abs(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_sinh
SEXP fwd_sinh(SEXP a);
RcppExport SEXP _xadr_fwd_sinh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_sinh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_cosh
SEXP fwd_cosh(SEXP a);
RcppExport SEXP _xadr_fwd_cosh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_cosh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_tanh
SEXP fwd_tanh(SEXP a);
RcppExport SEXP _xadr_fwd_tanh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_tanh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_asinh
SEXP fwd_asinh(SEXP a);
RcppExport SEXP _xadr_fwd_asinh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_asinh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_acosh
SEXP fwd_acosh(SEXP a);
RcppExport SEXP _xadr_fwd_acosh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_acosh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_atanh
SEXP fwd_atanh(SEXP a);
RcppExport SEXP _xadr_fwd_atanh(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_atanh(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_erf
SEXP fwd_erf(SEXP a);
RcppExport SEXP _xadr_fwd_erf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_erf(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_erfc
SEXP fwd_erfc(SEXP a);
RcppExport SEXP _xadr_fwd_erfc(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_erfc(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_floor
SEXP fwd_floor(SEXP a);
RcppExport SEXP _xadr_fwd_floor(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_floor(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_ceil
SEXP fwd_ceil(SEXP a);
RcppExport SEXP _xadr_fwd_ceil(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_ceil(a));
    return rcpp_result_gen;
END_RCPP
}
// fwd_hypot
SEXP fwd_hypot(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_hypot(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_hypot(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_min
SEXP fwd_min(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_min(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_min(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fwd_max
SEXP fwd_max(SEXP a, SEXP b);
RcppExport SEXP _xadr_fwd_max(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fwd_max(a, b));
    return rcpp_result_gen;
END_RCPP
}
// xad_version
std::string xad_version();
RcppExport SEXP _xadr_xad_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(xad_version());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xadr_adj_Real", (DL_FUNC) &_xadr_adj_Real, 1},
    {"_xadr_adj_getValue", (DL_FUNC) &_xadr_adj_getValue, 1},
    {"_xadr_adj_getDerivative", (DL_FUNC) &_xadr_adj_getDerivative, 1},
    {"_xadr_adj_setDerivative", (DL_FUNC) &_xadr_adj_setDerivative, 2},
    {"_xadr_adj_createTape", (DL_FUNC) &_xadr_adj_createTape, 0},
    {"_xadr_adj_deactivateTape", (DL_FUNC) &_xadr_adj_deactivateTape, 1},
    {"_xadr_adj_deactivateAll", (DL_FUNC) &_xadr_adj_deactivateAll, 0},
    {"_xadr_adj_registerInput", (DL_FUNC) &_xadr_adj_registerInput, 2},
    {"_xadr_adj_registerOutput", (DL_FUNC) &_xadr_adj_registerOutput, 2},
    {"_xadr_adj_newRecording", (DL_FUNC) &_xadr_adj_newRecording, 1},
    {"_xadr_adj_computeAdjoints", (DL_FUNC) &_xadr_adj_computeAdjoints, 1},
    {"_xadr_adj_clearDerivatives", (DL_FUNC) &_xadr_adj_clearDerivatives, 1},
    {"_xadr_adj_add", (DL_FUNC) &_xadr_adj_add, 2},
    {"_xadr_adj_add_scalar", (DL_FUNC) &_xadr_adj_add_scalar, 2},
    {"_xadr_adj_sub", (DL_FUNC) &_xadr_adj_sub, 2},
    {"_xadr_adj_sub_scalar", (DL_FUNC) &_xadr_adj_sub_scalar, 2},
    {"_xadr_adj_mul", (DL_FUNC) &_xadr_adj_mul, 2},
    {"_xadr_adj_mul_scalar", (DL_FUNC) &_xadr_adj_mul_scalar, 2},
    {"_xadr_adj_div", (DL_FUNC) &_xadr_adj_div, 2},
    {"_xadr_adj_div_scalar", (DL_FUNC) &_xadr_adj_div_scalar, 2},
    {"_xadr_adj_neg", (DL_FUNC) &_xadr_adj_neg, 1},
    {"_xadr_adj_sin", (DL_FUNC) &_xadr_adj_sin, 1},
    {"_xadr_adj_cos", (DL_FUNC) &_xadr_adj_cos, 1},
    {"_xadr_adj_tan", (DL_FUNC) &_xadr_adj_tan, 1},
    {"_xadr_adj_asin", (DL_FUNC) &_xadr_adj_asin, 1},
    {"_xadr_adj_acos", (DL_FUNC) &_xadr_adj_acos, 1},
    {"_xadr_adj_atan", (DL_FUNC) &_xadr_adj_atan, 1},
    {"_xadr_adj_atan2", (DL_FUNC) &_xadr_adj_atan2, 2},
    {"_xadr_adj_exp", (DL_FUNC) &_xadr_adj_exp, 1},
    {"_xadr_adj_exp2", (DL_FUNC) &_xadr_adj_exp2, 1},
    {"_xadr_adj_expm1", (DL_FUNC) &_xadr_adj_expm1, 1},
    {"_xadr_adj_log", (DL_FUNC) &_xadr_adj_log, 1},
    {"_xadr_adj_log2", (DL_FUNC) &_xadr_adj_log2, 1},
    {"_xadr_adj_log10", (DL_FUNC) &_xadr_adj_log10, 1},
    {"_xadr_adj_log1p", (DL_FUNC) &_xadr_adj_log1p, 1},
    {"_xadr_adj_sqrt", (DL_FUNC) &_xadr_adj_sqrt, 1},
    {"_xadr_adj_cbrt", (DL_FUNC) &_xadr_adj_cbrt, 1},
    {"_xadr_adj_pow", (DL_FUNC) &_xadr_adj_pow, 2},
    {"_xadr_adj_pow_scalar", (DL_FUNC) &_xadr_adj_pow_scalar, 2},
    {"_xadr_adj_abs", (DL_FUNC) &_xadr_adj_abs, 1},
    {"_xadr_adj_fabs", (DL_FUNC) &_xadr_adj_fabs, 1},
    {"_xadr_adj_sinh", (DL_FUNC) &_xadr_adj_sinh, 1},
    {"_xadr_adj_cosh", (DL_FUNC) &_xadr_adj_cosh, 1},
    {"_xadr_adj_tanh", (DL_FUNC) &_xadr_adj_tanh, 1},
    {"_xadr_adj_asinh", (DL_FUNC) &_xadr_adj_asinh, 1},
    {"_xadr_adj_acosh", (DL_FUNC) &_xadr_adj_acosh, 1},
    {"_xadr_adj_atanh", (DL_FUNC) &_xadr_adj_atanh, 1},
    {"_xadr_adj_erf", (DL_FUNC) &_xadr_adj_erf, 1},
    {"_xadr_adj_erfc", (DL_FUNC) &_xadr_adj_erfc, 1},
    {"_xadr_adj_floor", (DL_FUNC) &_xadr_adj_floor, 1},
    {"_xadr_adj_ceil", (DL_FUNC) &_xadr_adj_ceil, 1},
    {"_xadr_adj_round", (DL_FUNC) &_xadr_adj_round, 1},
    {"_xadr_adj_trunc", (DL_FUNC) &_xadr_adj_trunc, 1},
    {"_xadr_adj_min", (DL_FUNC) &_xadr_adj_min, 2},
    {"_xadr_adj_max", (DL_FUNC) &_xadr_adj_max, 2},
    {"_xadr_adj_fmax", (DL_FUNC) &_xadr_adj_fmax, 2},
    {"_xadr_adj_fmin", (DL_FUNC) &_xadr_adj_fmin, 2},
    {"_xadr_adj_hypot", (DL_FUNC) &_xadr_adj_hypot, 2},
    {"_xadr_adj_ldexp", (DL_FUNC) &_xadr_adj_ldexp, 2},
    {"_xadr_adj_fmod", (DL_FUNC) &_xadr_adj_fmod, 2},
    {"_xadr_adj_remainder", (DL_FUNC) &_xadr_adj_remainder, 2},
    {"_xadr_adj_copysign", (DL_FUNC) &_xadr_adj_copysign, 2},
    {"_xadr_fwd_Real", (DL_FUNC) &_xadr_fwd_Real, 1},
    {"_xadr_fwd_getValue", (DL_FUNC) &_xadr_fwd_getValue, 1},
    {"_xadr_fwd_getDerivative", (DL_FUNC) &_xadr_fwd_getDerivative, 1},
    {"_xadr_fwd_setDerivative", (DL_FUNC) &_xadr_fwd_setDerivative, 2},
    {"_xadr_fwd_add", (DL_FUNC) &_xadr_fwd_add, 2},
    {"_xadr_fwd_add_scalar", (DL_FUNC) &_xadr_fwd_add_scalar, 2},
    {"_xadr_fwd_sub", (DL_FUNC) &_xadr_fwd_sub, 2},
    {"_xadr_fwd_sub_scalar", (DL_FUNC) &_xadr_fwd_sub_scalar, 2},
    {"_xadr_fwd_mul", (DL_FUNC) &_xadr_fwd_mul, 2},
    {"_xadr_fwd_mul_scalar", (DL_FUNC) &_xadr_fwd_mul_scalar, 2},
    {"_xadr_fwd_div", (DL_FUNC) &_xadr_fwd_div, 2},
    {"_xadr_fwd_div_scalar", (DL_FUNC) &_xadr_fwd_div_scalar, 2},
    {"_xadr_fwd_neg", (DL_FUNC) &_xadr_fwd_neg, 1},
    {"_xadr_fwd_pow", (DL_FUNC) &_xadr_fwd_pow, 2},
    {"_xadr_fwd_pow_scalar", (DL_FUNC) &_xadr_fwd_pow_scalar, 2},
    {"_xadr_fwd_sin", (DL_FUNC) &_xadr_fwd_sin, 1},
    {"_xadr_fwd_cos", (DL_FUNC) &_xadr_fwd_cos, 1},
    {"_xadr_fwd_tan", (DL_FUNC) &_xadr_fwd_tan, 1},
    {"_xadr_fwd_asin", (DL_FUNC) &_xadr_fwd_asin, 1},
    {"_xadr_fwd_acos", (DL_FUNC) &_xadr_fwd_acos, 1},
    {"_xadr_fwd_atan", (DL_FUNC) &_xadr_fwd_atan, 1},
    {"_xadr_fwd_atan2", (DL_FUNC) &_xadr_fwd_atan2, 2},
    {"_xadr_fwd_exp", (DL_FUNC) &_xadr_fwd_exp, 1},
    {"_xadr_fwd_exp2", (DL_FUNC) &_xadr_fwd_exp2, 1},
    {"_xadr_fwd_expm1", (DL_FUNC) &_xadr_fwd_expm1, 1},
    {"_xadr_fwd_log", (DL_FUNC) &_xadr_fwd_log, 1},
    {"_xadr_fwd_log2", (DL_FUNC) &_xadr_fwd_log2, 1},
    {"_xadr_fwd_log10", (DL_FUNC) &_xadr_fwd_log10, 1},
    {"_xadr_fwd_log1p", (DL_FUNC) &_xadr_fwd_log1p, 1},
    {"_xadr_fwd_sqrt", (DL_FUNC) &_xadr_fwd_sqrt, 1},
    {"_xadr_fwd_cbrt", (DL_FUNC) &_xadr_fwd_cbrt, 1},
    {"_xadr_fwd_abs", (DL_FUNC) &_xadr_fwd_abs, 1},
    {"_xadr_fwd_sinh", (DL_FUNC) &_xadr_fwd_sinh, 1},
    {"_xadr_fwd_cosh", (DL_FUNC) &_xadr_fwd_cosh, 1},
    {"_xadr_fwd_tanh", (DL_FUNC) &_xadr_fwd_tanh, 1},
    {"_xadr_fwd_asinh", (DL_FUNC) &_xadr_fwd_asinh, 1},
    {"_xadr_fwd_acosh", (DL_FUNC) &_xadr_fwd_acosh, 1},
    {"_xadr_fwd_atanh", (DL_FUNC) &_xadr_fwd_atanh, 1},
    {"_xadr_fwd_erf", (DL_FUNC) &_xadr_fwd_erf, 1},
    {"_xadr_fwd_erfc", (DL_FUNC) &_xadr_fwd_erfc, 1},
    {"_xadr_fwd_floor", (DL_FUNC) &_xadr_fwd_floor, 1},
    {"_xadr_fwd_ceil", (DL_FUNC) &_xadr_fwd_ceil, 1},
    {"_xadr_fwd_hypot", (DL_FUNC) &_xadr_fwd_hypot, 2},
    {"_xadr_fwd_min", (DL_FUNC) &_xadr_fwd_min, 2},
    {"_xadr_fwd_max", (DL_FUNC) &_xadr_fwd_max, 2},
    {"_xadr_xad_version", (DL_FUNC) &_xadr_xad_version, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_xadr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
