# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname adj_math \
#' @export \
NULL

#' Create an adjoint-mode active real number
#'
#' @param v Initial value (default 0.0)
#' @return An external pointer to an AReal object
#' @export
adj_Real <- function(v = 0.0) {
    .Call(`_xadr_adj_Real`, v)
}

#' Get the value of an adjoint-mode active real
#'
#' @param xptr An XPtr to an AReal object (class "xad_adj_real")
#' @return The double value
#' @export
adj_getValue <- function(xptr) {
    .Call(`_xadr_adj_getValue`, xptr)
}

#' Get the derivative (adjoint) of an adjoint-mode active real
#'
#' @param xptr An XPtr to an AReal object
#' @return The derivative value
#' @export
adj_getDerivative <- function(xptr) {
    .Call(`_xadr_adj_getDerivative`, xptr)
}

#' Set the derivative (adjoint) of an adjoint-mode active real
#'
#' @param xptr An XPtr to an AReal object
#' @param d Derivative value to set
#' @export
adj_setDerivative <- function(xptr, d) {
    invisible(.Call(`_xadr_adj_setDerivative`, xptr, d))
}

#' Create an adjoint-mode tape
#'
#' @return An external pointer to a Tape object
#' @export
adj_createTape <- function() {
    .Call(`_xadr_adj_createTape`)
}

#' Deactivate an adjoint-mode tape (but do not destroy it)
#'
#' @param tape_ptr An XPtr to a Tape object
#' @export
adj_deactivateTape <- function(tape_ptr) {
    invisible(.Call(`_xadr_adj_deactivateTape`, tape_ptr))
}

#' Deactivate all tapes for the current thread
#'
#' @export
adj_deactivateAll <- function() {
    invisible(.Call(`_xadr_adj_deactivateAll`))
}

#' Register an input variable on the tape
#'
#' @param tape_ptr An XPtr to a Tape object
#' @param xptr An XPtr to an AReal object
#' @export
adj_registerInput <- function(tape_ptr, xptr) {
    invisible(.Call(`_xadr_adj_registerInput`, tape_ptr, xptr))
}

#' Register an output variable on the tape
#'
#' @param tape_ptr An XPtr to a Tape object
#' @param xptr An XPtr to an AReal object
#' @export
adj_registerOutput <- function(tape_ptr, xptr) {
    invisible(.Call(`_xadr_adj_registerOutput`, tape_ptr, xptr))
}

#' Start a new recording on the tape
#'
#' @param tape_ptr An XPtr to a Tape object
#' @export
adj_newRecording <- function(tape_ptr) {
    invisible(.Call(`_xadr_adj_newRecording`, tape_ptr))
}

#' Compute adjoints (backpropagate derivatives) on the tape
#'
#' @param tape_ptr An XPtr to a Tape object
#' @export
adj_computeAdjoints <- function(tape_ptr) {
    invisible(.Call(`_xadr_adj_computeAdjoints`, tape_ptr))
}

#' Clear all adjoints on the tape (keeping the recording)
#'
#' @param tape_ptr An XPtr to a Tape object
#' @export
adj_clearDerivatives <- function(tape_ptr) {
    invisible(.Call(`_xadr_adj_clearDerivatives`, tape_ptr))
}

#' Add two adjoint-mode active reals
#' @param a First XPtr to AReal
#' @param b Second XPtr to AReal
#' @return New XPtr to AReal (result)
#' @export
adj_add <- function(a, b) {
    .Call(`_xadr_adj_add`, a, b)
}

#' Add an adjoint-mode active real and a scalar
#' @param a XPtr to AReal
#' @param b Scalar double
#' @return New XPtr to AReal (result)
#' @export
adj_add_scalar <- function(a, b) {
    .Call(`_xadr_adj_add_scalar`, a, b)
}

#' Subtract two adjoint-mode active reals
#' @param a First XPtr to AReal
#' @param b Second XPtr to AReal
#' @return New XPtr to AReal (result)
#' @export
adj_sub <- function(a, b) {
    .Call(`_xadr_adj_sub`, a, b)
}

#' Subtract a scalar from an adjoint-mode active real
#' @param a XPtr to AReal
#' @param b Scalar double
#' @return New XPtr to AReal (result)
#' @export
adj_sub_scalar <- function(a, b) {
    .Call(`_xadr_adj_sub_scalar`, a, b)
}

#' Multiply two adjoint-mode active reals
#' @param a First XPtr to AReal
#' @param b Second XPtr to AReal
#' @return New XPtr to AReal (result)
#' @export
adj_mul <- function(a, b) {
    .Call(`_xadr_adj_mul`, a, b)
}

#' Multiply an adjoint-mode active real by a scalar
#' @param a XPtr to AReal
#' @param b Scalar double
#' @return New XPtr to AReal (result)
#' @export
adj_mul_scalar <- function(a, b) {
    .Call(`_xadr_adj_mul_scalar`, a, b)
}

#' Divide two adjoint-mode active reals
#' @param a First XPtr to AReal (numerator)
#' @param b Second XPtr to AReal (denominator)
#' @return New XPtr to AReal (result)
#' @export
adj_div <- function(a, b) {
    .Call(`_xadr_adj_div`, a, b)
}

#' Divide an adjoint-mode active real by a scalar
#' @param a XPtr to AReal (numerator)
#' @param b Scalar double (denominator)
#' @return New XPtr to AReal (result)
#' @export
adj_div_scalar <- function(a, b) {
    .Call(`_xadr_adj_div_scalar`, a, b)
}

#' Negate an adjoint-mode active real
#' @param a XPtr to AReal
#' @return New XPtr to AReal (negated)
#' @export
adj_neg <- function(a) {
    .Call(`_xadr_adj_neg`, a)
}

#' @export
adj_sin <- function(a) {
    .Call(`_xadr_adj_sin`, a)
}

#' @export
adj_cos <- function(a) {
    .Call(`_xadr_adj_cos`, a)
}

#' @export
adj_tan <- function(a) {
    .Call(`_xadr_adj_tan`, a)
}

#' @export
adj_asin <- function(a) {
    .Call(`_xadr_adj_asin`, a)
}

#' @export
adj_acos <- function(a) {
    .Call(`_xadr_adj_acos`, a)
}

#' @export
adj_atan <- function(a) {
    .Call(`_xadr_adj_atan`, a)
}

#' @export
adj_atan2 <- function(a, b) {
    .Call(`_xadr_adj_atan2`, a, b)
}

#' @export
adj_exp <- function(a) {
    .Call(`_xadr_adj_exp`, a)
}

#' @export
adj_exp2 <- function(a) {
    .Call(`_xadr_adj_exp2`, a)
}

#' @export
adj_expm1 <- function(a) {
    .Call(`_xadr_adj_expm1`, a)
}

#' @export
adj_log <- function(a) {
    .Call(`_xadr_adj_log`, a)
}

#' @export
adj_log2 <- function(a) {
    .Call(`_xadr_adj_log2`, a)
}

#' @export
adj_log10 <- function(a) {
    .Call(`_xadr_adj_log10`, a)
}

#' @export
adj_log1p <- function(a) {
    .Call(`_xadr_adj_log1p`, a)
}

#' @export
adj_sqrt <- function(a) {
    .Call(`_xadr_adj_sqrt`, a)
}

#' @export
adj_cbrt <- function(a) {
    .Call(`_xadr_adj_cbrt`, a)
}

#' @export
adj_pow <- function(a, b) {
    .Call(`_xadr_adj_pow`, a, b)
}

#' @export
adj_pow_scalar <- function(a, b) {
    .Call(`_xadr_adj_pow_scalar`, a, b)
}

#' @export
adj_abs <- function(a) {
    .Call(`_xadr_adj_abs`, a)
}

#' @export
adj_fabs <- function(a) {
    .Call(`_xadr_adj_fabs`, a)
}

#' @export
adj_sinh <- function(a) {
    .Call(`_xadr_adj_sinh`, a)
}

#' @export
adj_cosh <- function(a) {
    .Call(`_xadr_adj_cosh`, a)
}

#' @export
adj_tanh <- function(a) {
    .Call(`_xadr_adj_tanh`, a)
}

#' @export
adj_asinh <- function(a) {
    .Call(`_xadr_adj_asinh`, a)
}

#' @export
adj_acosh <- function(a) {
    .Call(`_xadr_adj_acosh`, a)
}

#' @export
adj_atanh <- function(a) {
    .Call(`_xadr_adj_atanh`, a)
}

#' @export
adj_erf <- function(a) {
    .Call(`_xadr_adj_erf`, a)
}

#' @export
adj_erfc <- function(a) {
    .Call(`_xadr_adj_erfc`, a)
}

#' @export
adj_floor <- function(a) {
    .Call(`_xadr_adj_floor`, a)
}

#' @export
adj_ceil <- function(a) {
    .Call(`_xadr_adj_ceil`, a)
}

#' @export
adj_round <- function(a) {
    .Call(`_xadr_adj_round`, a)
}

#' @export
adj_trunc <- function(a) {
    .Call(`_xadr_adj_trunc`, a)
}

#' @export
adj_min <- function(a, b) {
    .Call(`_xadr_adj_min`, a, b)
}

#' @export
adj_max <- function(a, b) {
    .Call(`_xadr_adj_max`, a, b)
}

#' @export
adj_fmax <- function(a, b) {
    .Call(`_xadr_adj_fmax`, a, b)
}

#' @export
adj_fmin <- function(a, b) {
    .Call(`_xadr_adj_fmin`, a, b)
}

#' @export
adj_hypot <- function(a, b) {
    .Call(`_xadr_adj_hypot`, a, b)
}

#' @export
adj_ldexp <- function(a, exp) {
    .Call(`_xadr_adj_ldexp`, a, exp)
}

#' @export
adj_fmod <- function(a, b) {
    .Call(`_xadr_adj_fmod`, a, b)
}

#' @export
adj_remainder <- function(a, b) {
    .Call(`_xadr_adj_remainder`, a, b)
}

#' @export
adj_copysign <- function(a, b) {
    .Call(`_xadr_adj_copysign`, a, b)
}

#' Create a forward-mode active real number
#'
#' @param v Initial value (default 0.0)
#' @return An external pointer to an FReal object
#' @export
fwd_Real <- function(v = 0.0) {
    .Call(`_xadr_fwd_Real`, v)
}

#' Get the value of a forward-mode active real
#'
#' @param xptr An XPtr to an FReal object (class "xad_fwd_real")
#' @return The double value
#' @export
fwd_getValue <- function(xptr) {
    .Call(`_xadr_fwd_getValue`, xptr)
}

#' Get the derivative of a forward-mode active real
#'
#' @param xptr An XPtr to an FReal object
#' @return The derivative value
#' @export
fwd_getDerivative <- function(xptr) {
    .Call(`_xadr_fwd_getDerivative`, xptr)
}

#' Set the derivative seed of a forward-mode active real
#'
#' @param xptr An XPtr to an FReal object
#' @param d Derivative value to set (seed)
#' @export
fwd_setDerivative <- function(xptr, d) {
    invisible(.Call(`_xadr_fwd_setDerivative`, xptr, d))
}

#' @export
fwd_add <- function(a, b) {
    .Call(`_xadr_fwd_add`, a, b)
}

#' @export
fwd_add_scalar <- function(a, b) {
    .Call(`_xadr_fwd_add_scalar`, a, b)
}

#' @export
fwd_sub <- function(a, b) {
    .Call(`_xadr_fwd_sub`, a, b)
}

#' @export
fwd_sub_scalar <- function(a, b) {
    .Call(`_xadr_fwd_sub_scalar`, a, b)
}

#' @export
fwd_mul <- function(a, b) {
    .Call(`_xadr_fwd_mul`, a, b)
}

#' @export
fwd_mul_scalar <- function(a, b) {
    .Call(`_xadr_fwd_mul_scalar`, a, b)
}

#' @export
fwd_div <- function(a, b) {
    .Call(`_xadr_fwd_div`, a, b)
}

#' @export
fwd_div_scalar <- function(a, b) {
    .Call(`_xadr_fwd_div_scalar`, a, b)
}

#' @export
fwd_neg <- function(a) {
    .Call(`_xadr_fwd_neg`, a)
}

#' @export
fwd_pow <- function(a, b) {
    .Call(`_xadr_fwd_pow`, a, b)
}

#' @export
fwd_pow_scalar <- function(a, b) {
    .Call(`_xadr_fwd_pow_scalar`, a, b)
}

#' @export
fwd_sin <- function(a) {
    .Call(`_xadr_fwd_sin`, a)
}

#' @export
fwd_cos <- function(a) {
    .Call(`_xadr_fwd_cos`, a)
}

#' @export
fwd_tan <- function(a) {
    .Call(`_xadr_fwd_tan`, a)
}

#' @export
fwd_asin <- function(a) {
    .Call(`_xadr_fwd_asin`, a)
}

#' @export
fwd_acos <- function(a) {
    .Call(`_xadr_fwd_acos`, a)
}

#' @export
fwd_atan <- function(a) {
    .Call(`_xadr_fwd_atan`, a)
}

#' @export
fwd_atan2 <- function(a, b) {
    .Call(`_xadr_fwd_atan2`, a, b)
}

#' @export
fwd_exp <- function(a) {
    .Call(`_xadr_fwd_exp`, a)
}

#' @export
fwd_exp2 <- function(a) {
    .Call(`_xadr_fwd_exp2`, a)
}

#' @export
fwd_expm1 <- function(a) {
    .Call(`_xadr_fwd_expm1`, a)
}

#' @export
fwd_log <- function(a) {
    .Call(`_xadr_fwd_log`, a)
}

#' @export
fwd_log2 <- function(a) {
    .Call(`_xadr_fwd_log2`, a)
}

#' @export
fwd_log10 <- function(a) {
    .Call(`_xadr_fwd_log10`, a)
}

#' @export
fwd_log1p <- function(a) {
    .Call(`_xadr_fwd_log1p`, a)
}

#' @export
fwd_sqrt <- function(a) {
    .Call(`_xadr_fwd_sqrt`, a)
}

#' @export
fwd_cbrt <- function(a) {
    .Call(`_xadr_fwd_cbrt`, a)
}

#' @export
fwd_abs <- function(a) {
    .Call(`_xadr_fwd_abs`, a)
}

#' @export
fwd_sinh <- function(a) {
    .Call(`_xadr_fwd_sinh`, a)
}

#' @export
fwd_cosh <- function(a) {
    .Call(`_xadr_fwd_cosh`, a)
}

#' @export
fwd_tanh <- function(a) {
    .Call(`_xadr_fwd_tanh`, a)
}

#' @export
fwd_asinh <- function(a) {
    .Call(`_xadr_fwd_asinh`, a)
}

#' @export
fwd_acosh <- function(a) {
    .Call(`_xadr_fwd_acosh`, a)
}

#' @export
fwd_atanh <- function(a) {
    .Call(`_xadr_fwd_atanh`, a)
}

#' @export
fwd_erf <- function(a) {
    .Call(`_xadr_fwd_erf`, a)
}

#' @export
fwd_erfc <- function(a) {
    .Call(`_xadr_fwd_erfc`, a)
}

#' @export
fwd_floor <- function(a) {
    .Call(`_xadr_fwd_floor`, a)
}

#' @export
fwd_ceil <- function(a) {
    .Call(`_xadr_fwd_ceil`, a)
}

#' @export
fwd_hypot <- function(a, b) {
    .Call(`_xadr_fwd_hypot`, a, b)
}

#' @export
fwd_min <- function(a, b) {
    .Call(`_xadr_fwd_min`, a, b)
}

#' @export
fwd_max <- function(a, b) {
    .Call(`_xadr_fwd_max`, a, b)
}

#' Get the XAD library version string
#'
#' @return A character string with the XAD version
#' @export
xad_version <- function() {
    .Call(`_xadr_xad_version`)
}

